name: Deploy to Render

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Add any test commands here, like pytest
        echo "Running tests"

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Make sure to add this secret in GitHub
      run: |
        curl -X POST \
        -H 'Authorization: Bearer $RENDER_API_KEY' \
        -H 'Content-Type: application/json' \
        --data '{"serviceId": "YOUR_SERVICE_ID", "clearCache": false}' \
        https://api.render.com/v1/services/YOUR_SERVICE_ID/deploys
